parameters:
    weather_provider: open_weather_map
    city_provider: '%env(json:VITBER_CITIES)%'

services:
    _instanceof:
        Vitber\WeatherBundle\Service\WeatherProvider\NamedWeatherProviderInterface:
            tags: [ 'vitber.weather_provider' ]

    Vitber\WeatherBundle\Service\WeatherProvider\WeatherProviderInterface: '@Vitber\WeatherBundle\Service\WeatherProvider\WeatherProvider'

    # City Providers
    Vitber\WeatherBundle\Service\CityProvider\CityProvider:
        arguments:
            - '%city_provider%'

    # Weather Providers
    Vitber\WeatherBundle\Service\WeatherProvider\WeatherProvider:
        arguments:
            - '@Vitber\WeatherBundle\Service\CityProvider\CityProvider'
            - !tagged_iterator { tag: 'vitber.weather_provider' }
            - '%weather_provider%'

    Vitber\WeatherBundle\Service\WeatherProvider\CachedWeatherProvider:
        decorates: Vitber\WeatherBundle\Service\WeatherProvider\WeatherProvider
        arguments:
            - '@.inner'
            - '@cache.app'

    Vitber\WeatherBundle\Service\WeatherProvider\OpenWeatherMap\OpenWeatherMapProvider:
        arguments:
            - '@Symfony\Contracts\HttpClient\HttpClientInterface'
            - ''
            - []
