services:
    _instanceof:
        Vitber\WeatherBundle\WeatherProvider\NamedWeatherProviderInterface:
            tags: [ 'vitber.weather_provider' ]

    Vitber\WeatherBundle\WeatherProvider\WeatherProviderInterface: '@Vitber\WeatherBundle\WeatherProvider\WeatherProvider'

    Vitber\WeatherBundle\CityProvider\CityProvider: ~

    # Weather Providers
    Vitber\WeatherBundle\WeatherProvider\WeatherProvider:
        arguments:
            - '@Vitber\WeatherBundle\CityProvider\CityProvider'
            - !tagged_iterator { tag: 'vitber.weather_provider' }
            - '@event_dispatcher'
            - '%weather_provider%'

    Vitber\WeatherBundle\Twig\CityTwigExtension:
        arguments:
            - '@Vitber\WeatherBundle\CityProvider\CityProvider'
        tags:
            - { name: twig.extension }

    Vitber\WeatherBundle\WeatherProvider\CachedWeatherProvider:
        decorates: Vitber\WeatherBundle\WeatherProvider\WeatherProvider
        arguments:
            - '@.inner'
            - '@cache.app'

    Vitber\WeatherBundle\WeatherProvider\OpenWeatherMap\OpenWeatherMapProvider:
        arguments:
            - '@Symfony\Contracts\HttpClient\HttpClientInterface'
            - '@logger'
            - ''
            - ''
            - ''
